include:
  - "**/*.rb"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
