require("my.base")
require("my.options")
require("my.keymaps")
require("my.filetypes")
require("my.lazy")
require("my.colorscheme")

if not vim.g.vscode then
  require("plugins.lualine")
  require("plugins.bufferline")
  require("plugins.telescope")
  require("plugins.neo_tree")
  require("plugins.indent_blankline")
  require("plugins.scrollbar")
  require("plugins.lspconfig")
  require("plugins.completion")
  require("plugins.git")
  require("plugins.gitsigns")
  require("plugins.null_ls")
  require("plugins.illuminate")
  -- require("plugins.hop")
  require("plugins.avante")
else
  require("my.vscode")
end
