require("my.base")
require("my.options")
require("my.keymaps")
require("my.filetypes")
require("my.plugins")
require("my.colorscheme")
-- require("my.binary")

require("plugins.lualine")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.neo_tree")
require("plugins.window_picker")
require("plugins.indent_blankline")
require("plugins.toggleterm")
require("plugins.scrollbar")
require("plugins.lspconfig")
require("plugins.completion")
require("plugins.git")
require("plugins.null_ls")
require("plugins.illuminate")
